module.exports = {
  stories: [
    "../src/**/*.stories.@(js|jsx|ts|tsx)",
    "../server/**/*.server.stories.@(js|jsx|ts|tsx)",
  ],
  addons: ["@storybook/addon-links", "@storybook/preset-scss"],
  webpackFinal: (config) => {
    config.module.rules = [
      ...config.module.rules,
      {
        test: /\.(ogg)$/,
        loader: "file-loader",
      },
    ];
    config.module.unknownContextCritical = false;
    config.optimization = {
      minimize: false,
      minimizer: [],
    };
    config.resolve.alias["@/rx.js"] = require.resolve("../src/rx.js");
    const esArrayModules = [
      "esnext.global-this",
      "es.symbol",
      "es.symbol.description",
      "es.symbol.iterator",
      "es.symbol.to-string-tag",
      "es.regexp.exec",
      "es.regexp.constructor",
      "es.regexp.to-string",
      "es.string.includes",
      "es.string.split",
      "es.string.replace",
      "es.string.iterator",
      "es.string.match",
      "es.string.trim",
      "web.dom-collections.iterator",
      "web.dom-collections.for-each",
      "es.array.concat",
      "es.array.every",
      "es.array.filter",
      "es.array.find",
      "es.array.find-index",
      "es.array.for-each",
      "es.array.index-of",
      "es.array.iterator",
      "es.array.includes",
      "es.array.join",
      "es.array.map",
      "es.array.some",
      "es.array.slice",
      "es.array.splice",
      "es.array.reduce",
      "es.json.to-string-tag",
      "es.function.name",
      "es.global-this",
      "es.math.to-string-tag",
      "es.typed-array.copy-within",
      "es.typed-array.every",
      "es.typed-array.fill",
      "es.typed-array.filter",
      "es.typed-array.find",
      "es.typed-array.find-index",
      "es.typed-array.for-each",
      "es.typed-array.includes",
      "es.typed-array.index-of",
      "es.typed-array.iterator",
      "es.typed-array.join",
      "es.typed-array.last-index-of",
      "es.typed-array.map",
      "es.typed-array.reduce",
      "es.typed-array.reduce-right",
      "es.typed-array.reverse",
      "es.typed-array.set",
      "es.typed-array.slice",
      "es.typed-array.some",
      "es.typed-array.sort",
      "es.typed-array.subarray",
      "es.typed-array.to-locale-string",
      "es.typed-array.to-string",
      "es.typed-array.uint32-array",
      "es.number.constructor",
      "es.number.max-safe-integer",
      "es.number.to-fixed",
      "es.object.assign",
      "es.object.get-own-property-names",
      "es.object.get-own-property-descriptor",
      "es.object.get-own-property-descriptors",
      "es.object.keys",
      "es.object.values",
      "es.object.to-string",
      "es.promise",
      "es.promise.finally",
      "es.weak-map",
    ];
    esArrayModules.forEach((name) => {
      config.resolve.alias[`core-js/modules/${name}`] = require.resolve(
        `../node_modules/@storybook/core/node_modules/core-js/modules/${name}.js`
      );
    });
    return config;
  },
};
